export const DATA = [
    {
      "name": "Virat Kohli",
      "country": "India",
      "runs": 25643,
      "average": 53.51,
      "strikeRate": 79.83,
      "centuries": 75,
      "halfCenturies": 133,
      "photo": "https://example.com/virat-kohli.jpg",
      "wickets": 4,
      "economy": 6.22,
      "fiveWicketHauls": 0
    },
    {
      "name": "Joe Root",
      "country": "England",
      "runs": 18775,
      "average": 49.41,
      "strikeRate": 72.32,
      "centuries": 46,
      "halfCenturies": 90,
      "photo": "https://example.com/joe-root.jpg",
      "wickets": 52,
      "economy": 4.87,
      "fiveWicketHauls": 0
    },
    {
      "name": "Kane Williamson",
      "country": "New Zealand",
      "runs": 18074,
      "average": 50.99,
      "strikeRate": 69.01,
      "centuries": 40,
      "halfCenturies": 96,
      "photo": "https://example.com/kane-williamson.jpg",
      "wickets": 29,
      "economy": 4.93,
      "fiveWicketHauls": 0
    },
    {
      "name": "Steve Smith",
      "country": "Australia",
      "runs": 17995,
      "average": 54.07,
      "strikeRate": 72.64,
      "centuries": 43,
      "halfCenturies": 89,
      "photo": "https://example.com/steve-smith.jpg",
      "wickets": 17,
      "economy": 5.54,
      "fiveWicketHauls": 0
    },
    {
      "name": "Rohit Sharma",
      "country": "India",
      "runs": 17623,
      "average": 46.12,
      "strikeRate": 85.73,
      "centuries": 43,
      "halfCenturies": 90,
      "photo": "https://example.com/rohit-sharma.jpg",
      "wickets": 8,
      "economy": 5.92,
      "fiveWicketHauls": 0
    },
    {
      "name": "Ben Stokes",
      "country": "England",
      "runs": 12092,
      "average": 36.18,
      "strikeRate": 87.12,
      "centuries": 16,
      "halfCenturies": 61,
      "photo": "https://example.com/ben-stokes.jpg",
      "wickets": 254,
      "economy": 4.72,
      "fiveWicketHauls": 4
    },
    {
      "name": "Babar Azam",
      "country": "Pakistan",
      "runs": 11808,
      "average": 49.41,
      "strikeRate": 84.36,
      "centuries": 28,
      "halfCenturies": 68,
      "photo": "https://example.com/babar-azam.jpg",
      "wickets": 0,
      "economy": 0,
      "fiveWicketHauls": 0
    },
    {
      "name": "David Warner",
      "country": "Australia",
      "runs": 17563,
      "average": 42.35,
      "strikeRate": 90.78,
      "centuries": 45,
      "halfCenturies": 89,
      "photo": "https://example.com/david-warner.jpg",
      "wickets": 4,
      "economy": 7.38,
      "fiveWicketHauls": 0
    },
    {
      "name": "Ross Taylor",
      "country": "New Zealand",
      "runs": 18074,
      "average": 44.87,
      "strikeRate": 79.21,
      "centuries": 40,
      "halfCenturies": 93,
      "photo": "https://example.com/ross-taylor.jpg",
      "wickets": 3,
      "economy": 5.33,
      "fiveWicketHauls": 0
    },
    {
      "name": "Shakib Al Hasan",
      "country": "Bangladesh",
      "runs": 13129,
      "average": 37.05,
      "strikeRate": 82.14,
      "centuries": 14,
      "halfCenturies": 85,
      "photo": "https://example.com/shakib-al-hasan.jpg",
      "wickets": 622,
      "economy": 4.43,
      "fiveWicketHauls": 18
    },
    {
      "name": "Jos Buttler",
      "country": "England",
      "runs": 9889,
      "average": 38.92,
      "strikeRate": 119.54,
      "centuries": 15,
      "halfCenturies": 53,
      "photo": "https://example.com/jos-buttler.jpg",
      "wickets": 0,
      "economy": 0,
      "fiveWicketHauls": 0
    },
    {
      "name": "Quinton de Kock",
      "country": "South Africa",
      "runs": 10889,
      "average": 38.94,
      "strikeRate": 95.21,
      "centuries": 21,
      "halfCenturies": 56,
      "photo": "https://example.com/quinton-de-kock.jpg",
      "wickets": 0,
      "economy": 0,
      "fiveWicketHauls": 0
    },
    {
      "name": "Jasprit Bumrah",
      "country": "India",
      "runs": 112,
      "average": 6.22,
      "strikeRate": 54.63,
      "centuries": 0,
      "halfCenturies": 0,
      "photo": "https://example.com/jasprit-bumrah.jpg",
      "wickets": 364,
      "economy": 4.62,
      "fiveWicketHauls": 8
    },
    {
      "name": "Kagiso Rabada",
      "country": "South Africa",
      "runs": 534,
      "average": 11.86,
      "strikeRate": 65.84,
      "centuries": 0,
      "halfCenturies": 0,
      "photo": "https://example.com/kagiso-rabada.jpg",
      "wickets": 358,
      "economy": 4.89,
      "fiveWicketHauls": 12
    },
    {
      "name": "Trent Boult",
      "country": "New Zealand",
      "runs": 760,
      "average": 13.81,
      "strikeRate": 85.01,
      "centuries": 0,
      "halfCenturies": 0,
      "photo": "https://example.com/trent-boult.jpg",
      "wickets": 547,
      "economy": 4.92,
      "fiveWicketHauls": 10
    },
    {
      "name": "Mitchell Starc",
      "country": "Australia",
      "runs": 1920,
      "average": 22.58,
      "strikeRate": 100.62,
      "centuries": 0,
      "halfCenturies": 10,
      "photo": "https://example.com/mitchell-starc.jpg",
      "wickets": 503,
      "economy": 5.18,
      "fiveWicketHauls": 13
    },
    {
      "name": "Rashid Khan",
      "country": "Afghanistan",
      "runs": 1565,
      "average": 17.38,
      "strikeRate": 108.22,
      "centuries": 0,
      "halfCenturies": 3,
      "photo": "https://example.com/rashid-khan.jpg",
      "wickets": 468,
      "economy": 4.16,
      "fiveWicketHauls": 7
    },
    {
      "name": "Pat Cummins",
      "country": "Australia",
      "runs": 1620,
      "average": 18.62,
      "strikeRate": 75.45,
      "centuries": 0,
      "halfCenturies": 2,
      "photo": "https://example.com/pat-cummins.jpg",
      "wickets": 385,
      "economy": 4.62,
      "fiveWicketHauls": 8
    },
    {
      "name": "Ravichandran Ashwin",
      "country": "India",
      "runs": 3751,
      "average": 26.78,
      "strikeRate": 82.45,
      "centuries": 5,
      "halfCenturies": 13,
      "photo": "https://example.com/ravichandran-ashwin.jpg",
      "wickets": 710,
      "economy": 4.47,
      "fiveWicketHauls": 30
    },
    {
      "name": "Ravindra Jadeja",
      "country": "India",
      "runs": 5527,
      "average": 33.29,
      "strikeRate": 86.32,
      "centuries": 3,
      "halfCenturies": 29,
      "photo": "https://example.com/ravindra-jadeja.jpg",
      "wickets": 482,
      "economy": 4.62,
      "fiveWicketHauls": 9
    },
    {
      "name": "Faf du Plessis",
      "country": "South Africa",
      "runs": 12333,
      "average": 44.76,
      "strikeRate": 84.72,
      "centuries": 25,
      "halfCenturies": 63,
      "photo": "https://example.com/faf-du-plessis.jpg",
      "wickets": 2,
      "economy": 6.50,
      "fiveWicketHauls": 0
    },
    {
      "name": "AB de Villiers",
      "country": "South Africa",
      "runs": 20014,
      "average": 48.11,
      "strikeRate": 95.26,
      "centuries": 47,
      "halfCenturies": 109,
      "photo": "https://example.com/ab-de-villiers.jpg",
      "wickets": 2,
      "economy": 7.36,
      "fiveWicketHauls": 0
    },
    {
      "name": "Hashim Amla",
      "country": "South Africa",
      "runs": 18672,
      "average": 46.68,
      "strikeRate": 77.41,
      "centuries": 55,
      "halfCenturies": 88,
      "photo": "https://example.com/hashim-amla.jpg",
      "wickets": 0,
      "economy": 0,
      "fiveWicketHauls": 0
    },
    {
      "name": "Chris Gayle",
      "country": "West Indies",
      "runs": 19526,
      "average": 41.46,
      "strikeRate": 92.54,
      "centuries": 42,
      "halfCenturies": 96,
      "photo": "https://example.com/chris-gayle.jpg",
      "wickets": 85,
      "economy": 5.17,
      "fiveWicketHauls": 0
    },
    {
      "name": "MS Dhoni",
      "country": "India",
      "runs": 17266,
      "average": 44.96,
      "strikeRate": 87.56,
      "centuries": 16,
      "halfCenturies": 108,
      "photo": "https://example.com/ms-dhoni.jpg",
      "wickets": 1,
      "economy": 5.33,
      "fiveWicketHauls": 0
    },
    {
        "name": "Kumar Sangakkara",
        "country": "Sri Lanka",
        "runs": 28016,
        "average": 46.77,
        "strikeRate": 78.86,
        "centuries": 63,
        "halfCenturies": 153,
        "photo": "https://example.com/kumar-sangakkara.jpg",
        "wickets": 0,
        "economy": 0,
        "fiveWicketHauls": 0
    },
    {
        "name": "Mahela Jayawardene",
        "country": "Sri Lanka",
        "runs": 25957,
        "average": 39.16,
        "strikeRate": 77.67,
        "centuries": 54,
        "halfCenturies": 136,
        "photo": "https://example.com/mahela-jayawardene.jpg",
        "wickets": 8,
        "economy": 4.93,
        "fiveWicketHauls": 0
    },
    {
        "name": "Jacques Kallis",
        "country": "South Africa",
        "runs": 25534,
        "average": 55.37,
        "strikeRate": 72.89,
        "centuries": 62,
        "halfCenturies": 149,
        "photo": "https://example.com/jacques-kallis.jpg",
        "wickets": 577,
        "economy": 4.01,
        "fiveWicketHauls": 5
    },
    {
        "name": "Ricky Ponting",
        "country": "Australia",
        "runs": 27483,
        "average": 45.95,
        "strikeRate": 79.77,
        "centuries": 71,
        "halfCenturies": 146,
        "photo": "https://example.com/ricky-ponting.jpg",
        "wickets": 8,
        "economy": 5.58,
        "fiveWicketHauls": 0
    },
    {
        "name": "Sachin Tendulkar",
        "country": "India",
        "runs": 34357,
        "average": 48.52,
        "strikeRate": 79.09,
        "centuries": 100,
        "halfCenturies": 164,
        "photo": "https://example.com/sachin-tendulkar.jpg",
        "wickets": 201,
        "economy": 4.97,
        "fiveWicketHauls": 0
    },
    {
        "name": "Glenn McGrath",
        "country": "Australia",
        "runs": 641,
        "average": 7.36,
        "strikeRate": 57.23,
        "centuries": 0,
        "halfCenturies": 0,
        "photo": "https://example.com/glenn-mcgrath.jpg",
        "wickets": 949,
        "economy": 3.88,
        "fiveWicketHauls": 29
    },
    {
        "name": "Shane Warne",
        "country": "Australia",
        "runs": 3154,
        "average": 17.32,
        "strikeRate": 57.65,
        "centuries": 0,
        "halfCenturies": 12,
        "photo": "https://example.com/shane-warne.jpg",
        "wickets": 1001,
        "economy": 4.25,
        "fiveWicketHauls": 37
    },
    {
        "name": "Muttiah Muralitharan",
        "country": "Sri Lanka",
        "runs": 1261,
        "average": 11.67,
        "strikeRate": 54.98,
        "centuries": 0,
        "halfCenturies": 1,
        "photo": "https://example.com/muttiah-muralitharan.jpg",
        "wickets": 1347,
        "economy": 3.93,
        "fiveWicketHauls": 67
    },
    {
        "name": "James Anderson",
        "country": "England",
        "runs": 1285,
        "average": 8.74,
        "strikeRate": 42.61,
        "centuries": 0,
        "halfCenturies": 1,
        "photo": "https://example.com/james-anderson.jpg",
        "wickets": 949,
        "economy": 4.10,
        "fiveWicketHauls": 31
    },
    {
        "name": "Stuart Broad",
        "country": "England",
        "runs": 3425,
        "average": 18.21,
        "strikeRate": 65.24,
        "centuries": 1,
        "halfCenturies": 13,
        "photo": "https://example.com/stuart-broad.jpg",
        "wickets": 847,
        "economy": 4.32,
        "fiveWicketHauls": 18
    },
    {
        "name": "Dale Steyn",
        "country": "South Africa",
        "runs": 1251,
        "average": 12.51,
        "strikeRate": 55.60,
        "centuries": 0,
        "halfCenturies": 0,
        "photo": "https://example.com/dale-steyn.jpg",
        "wickets": 699,
        "economy": 4.70,
        "fiveWicketHauls": 26
    },
    {
        "name": "Lasith Malinga",
        "country": "Sri Lanka",
        "runs": 871,
        "average": 8.80,
        "strikeRate": 74.57,
        "centuries": 0,
        "halfCenturies": 0,
        "photo": "https://example.com/lasith-malinga.jpg",
        "wickets": 546,
        "economy": 5.35,
        "fiveWicketHauls": 8
    },
    {
        "name": "Shahid Afridi",
        "country": "Pakistan",
        "runs": 11196,
        "average": 23.57,
        "strikeRate": 116.80,
        "centuries": 11,
        "halfCenturies": 51,
        "photo": "https://example.com/shahid-afridi.jpg",
        "wickets": 541,
        "economy": 4.62,
        "fiveWicketHauls": 8
    },
    {
        "name": "Shoaib Akhtar",
        "country": "Pakistan",
        "runs": 544,
        "average": 9.72,
        "strikeRate": 81.92,
        "centuries": 0,
        "halfCenturies": 0,
        "photo": "https://example.com/shoaib-akhtar.jpg",
        "wickets": 444,
        "economy": 4.76,
        "fiveWicketHauls": 15
    },
    {
        "name": "Yuvraj Singh",
        "country": "India",
        "runs": 11778,
        "average": 33.92,
        "strikeRate": 87.67,
        "centuries": 17,
        "halfCenturies": 71,
        "photo": "https://example.com/yuvraj-singh.jpg",
        "wickets": 148,
        "economy": 5.10,
        "fiveWicketHauls": 1
    },
    {
        "name": "Brendon McCullum",
        "country": "New Zealand",
        "runs": 14676,
        "average": 38.64,
        "strikeRate": 79.75,
        "centuries": 17,
        "halfCenturies": 80,
        "photo": "https://example.com/brendon-mccullum.jpg",
        "wickets": 0,
        "economy": 0,
        "fiveWicketHauls": 0
    },
    {
        "name": "Eoin Morgan",
        "country": "England",
        "runs": 10859,
        "average": 39.29,
        "strikeRate": 91.73,
        "centuries": 16,
        "halfCenturies": 65,
        "photo": "https://example.com/eoin-morgan.jpg",
        "wickets": 0,
        "economy": 0,
        "fiveWicketHauls": 0
    },
    {
        "name": "Shikhar Dhawan",
        "country": "India",
        "runs": 10956,
        "average": 44.11,
        "strikeRate": 93.79,
        "centuries": 24,
        "halfCenturies": 55,
        "photo": "https://example.com/shikhar-dhawan.jpg",
        "wickets": 4,
        "economy": 5.63,
        "fiveWicketHauls": 0
    },
    {
        "name": "Mitchell Johnson",
        "country": "Australia",
        "runs": 2181,
        "average": 13.88,
        "strikeRate": 79.67,
        "centuries": 1,
        "halfCenturies": 11,
        "photo": "https://example.com/mitchell-johnson.jpg",
        "wickets": 590,
        "economy": 4.88,
        "fiveWicketHauls": 12
    },
    {
        "name": "Suresh Raina",
        "country": "India",
        "runs": 12286,
        "average": 35.44,
        "strikeRate": 93.50,
        "centuries": 17,
        "halfCenturies": 71,
        "photo": "https://example.com/suresh-raina.jpg",
        "wickets": 62,
        "economy": 5.09,
        "fiveWicketHauls": 0
    },
    {
        "name": "Dimuth Karunaratne",
        "country": "Sri Lanka",
        "runs": 5620,
        "average": 39.57,
        "strikeRate": 52.11,
        "centuries": 14,
        "halfCenturies": 29,
        "photo": "https://example.com/dimuth-karunaratne.jpg",
        "wickets": 0,
        "economy": 0,
        "fiveWicketHauls": 0
    },
    {
        "name": "Kusal Perera",
        "country": "Sri Lanka",
        "runs": 3910,
        "average": 31.03,
        "strikeRate": 92.63,
        "centuries": 5,
        "halfCenturies": 22,
        "photo": "https://example.com/kusal-perera.jpg",
        "wickets": 0,
        "economy": 0,
        "fiveWicketHauls": 0
    },
    {
        "name": "Mushfiqur Rahim",
        "country": "Bangladesh",
        "runs": 11819,
        "average": 36.76,
        "strikeRate": 79.31,
        "centuries": 16,
        "halfCenturies": 69,
        "photo": "https://example.com/mushfiqur-rahim.jpg",
        "wickets": 0,
        "economy": 0,
        "fiveWicketHauls": 0
    },
    {
        "name": "Tamim Iqbal",
        "country": "Bangladesh",
        "runs": 14387,
        "average": 36.62,
        "strikeRate": 78.45,
        "centuries": 25,
        "halfCenturies": 90,
        "photo": "https://example.com/tamim-iqbal.jpg",
        "wickets": 0,
        "economy": 0,
        "fiveWicketHauls": 0
    },
    {
        "name": "Martin Guptill",
        "country": "New Zealand",
        "runs": 10150,
        "average": 37.04,
        "strikeRate": 95.49,
        "centuries": 17,
        "halfCenturies": 55,
        "photo": "https://example.com/martin-guptill.jpg",
        "wickets": 4,
        "economy": 6.48,
        "fiveWicketHauls": 0
    }
]